import java.util.HashMap;

public class Registers 
{

	
        private HashMap<String,Word> registerMap;
        
	Registers()
        {
            registerMap = new HashMap<String,Word>();
            registerMap.put("R0", new Word());
            registerMap.put("R1", new Word());
            registerMap.put("R2", new Word());
            registerMap.put("R3", new Word());
            registerMap.put("X1", new Word());
            registerMap.put("X2", new Word());
            registerMap.put("X3", new Word());
            registerMap.put("PC", new Word());
            registerMap.put("IR", new Word());
            registerMap.put("CC", new Word());
            registerMap.put("MAR", new Word());
            registerMap.put("MBR", new Word());
            registerMap.put("MFR", new Word());
            
            for( Word register : registerMap.values())                
            {
                register.setData("0000000000000000");
            }
            
	}
	
	//setters and getters generated by eclipse
        public Word getRegister(RegisterMapping register)
        {
            return registerMap.get(register);
        }
        
	public Word getR0() {
		return registerMap.get("R0");
	}
	public void setR0(String r0) {
		registerMap.get("R0").setData(r0);
	}
	public Word getR1() {
		return registerMap.get("R1");
	}
	public void setR1(String r1) {
		registerMap.get("R1").setData(r1);
	}
	public Word getR2() {
		return registerMap.get("R2");
	}
	public void setR2(String r2) {
		registerMap.get("R2").setData(r2);
	}
	public Word getR3() {
		return registerMap.get("R3");
	}
	public void setR3(String r3) {
		registerMap.get("R3").setData(r3);
	}
	public Word getX1() {
		return registerMap.get("X1");
	}
	public void setX1(String x1) {
		registerMap.get("X1").setData(x1);
	}
	public Word getX2() {
		return registerMap.get("X2");
	}
	public void setX2(String x2) {
		registerMap.get("X2").setData(x2);
	}
	public Word getX3() {
		return registerMap.get("X3");
	}
	public void setX3(String x3) {
		registerMap.get("X3").setData(x3);
	}
	public Word getPC() {
		return registerMap.get("PC");
	}
	public void setPC(String pC) {
		registerMap.get("PC").setData(pC);
	}
	public Word getMAR() {
		return registerMap.get("MAR");
	}
	public void setMAR(String mAR) {
		registerMap.get("MAR").setData(mAR);
	}
	public Word getIR() {
		return registerMap.get("IR");
	}
	public void setIR(String iR) {
		registerMap.get("IR").setData(iR);
	}
	public Word getMBR() {
		return registerMap.get("MBR");
	}
	public void setMBR(String mBR) {
		registerMap.get("MBR").setData(mBR);
	}
	public Word getMFR() {
		return registerMap.get("MFR");
	}
	public void setMFR(String mFR) {
		registerMap.get("MFR").setData(mFR);
	}
}
