
public class Registers {
	//general purpose registers. 16 bits
	private String R0, R1, R2, R3;
	//index registers. 16 bits
	private String X1, X2, X3;
	//program counter. 12 bits
	private String PC;
	//memory address register. 16 bits
	private String MAR;
	//instruction register. 16 bits
	private String IR;
	//memory buffer register. 16 bits
	private String MBR;
	//machine fault register. 4 bits
	private String MFR;
	//condition code register. 4 bits
	private int CC0, CC1, CC2, CC3;
	//floating point register FR0 and FR1
	private String FR0, FR1;
	
	private static Registers inst = null;
	
	Registers(){
		R0 = "0000000000000000";
		R1 = "0000000000000000";
		R2 = "0000000000000000";
		R3 = "0000000000000000";
		X1 = "0000000000000000";
		X2 = "0000000000000000";
		X3 = "0000000000000000";
		PC = "000000000000";
		MAR = "0000000000000000";
		MBR = "0000000000000000";
		IR = "0000000000000000";
		MFR = "0000";
		CC0 = 0;
		CC1 = 0;
		CC2 = 0;
		CC3 = 0;
	}
	
	public static Registers instance()
    {
        if(inst == null)
        {
            inst = new Registers();
        }
        
        return inst;
    }
        
    public void reset()
    {
        R0 = "0000000000000000";
        R1 = "0000000000000000";
        R2 = "0000000000000000";
        R3 = "0000000000000000";
        X1 = "0000000000000000";
        X2 = "0000000000000000";
        X3 = "0000000000000000";
        PC = "000000000000";
        MAR = "0000000000000000";
        MBR = "0000000000000000";
        IR = "0000000000000000";
        MFR = "0000";
        CC0 = 0;
        CC1 = 0;
        CC2 = 0;
        CC3 = 0;
    }
	
	//setters and getters generated by eclipse
	public String getR0() {
		return R0;
	}
	public void setR0(String r0) {
		R0 = r0;
	}
	public String getR1() {
		return R1;
	}
	public void setR1(String r1) {
		R1 = r1;
	}
	public String getR2() {
		return R2;
	}
	public void setR2(String r2) {
		R2 = r2;
	}
	public String getR3() {
		return R3;
	}
	public void setR3(String r3) {
		R3 = r3;
	}
	public String getX1() {
		return X1;
	}
	public void setX1(String x1) {
		X1 = x1;
	}
	public String getX2() {
		return X2;
	}
	public void setX2(String x2) {
		X2 = x2;
	}
	public String getX3() {
		return X3;
	}
	public void setX3(String x3) {
		X3 = x3;
	}
	public String getPC() {
		return PC;
	}
	public void setPC(String pC) {
		PC = pC;
	}
	public String getMAR() {
		return MAR;
	}
	public void setMAR(String mAR) {
		MAR = mAR;
	}
	public String getIR() {
		return IR;
	}
	public void setIR(String iR) {
		IR = iR;
	}
	public String getMBR() {
		return MBR;
	}
	public void setMBR(String mBR) {
		MBR = mBR;
	}
	public String getMFR() {
		return MFR;
	}
	public void setMFR(String mFR) {
		MFR = mFR;
	}
	public int getCC0() {
		return CC0;
	}
	public void setCC0(int cC0) {
		CC0 = cC0;
	}
	public int getCC1() {
		return CC1;
	}
	public void setCC1(int cC1) {
		CC1 = cC1;
	}
	public int getCC2() {
		return CC2;
	}
	public void setCC2(int cC2) {
		CC2 = cC2;
	}
	public int getCC3() {
		return CC3;
	}
	public void setCC3(int cC3) {
		CC3 = cC3;
	}
	public String getFR0() {
		return FR0;
	}
	public void setFR0(String fR0) {
		FR0 = fR0;
	}
	public String getFR1() {
		return FR1;
	}
	public void setFR1(String fR1) {
		FR1 = fR1;
	}
}
